import test from 'node:test';import assert from 'node:assert/strict';import {parseGenetics,SAMPLE,DPYD_SAMPLE,MARKERS} from '../dist/genetics.mjs';import {deriveInsights} from '../dist/insights.mjs';import {replayFindings} from '../scripts/replay-findings.mjs';
const rules=MARKERS.filter(m=>m.gene==='DPYD');
const modify=(m,call,text=SAMPLE)=>text.replace(`${m.position}\t${m.reference}${m.reference}`,`${m.position}\t${call}`);
test('Each direct DPYD alternate triggers its own exact genomic basis',()=>{for(const m of rules)for(const call of [m.reference+m.alternate,m.alternate+m.alternate]){const r=parseGenetics(modify(m,call));const card=deriveInsights(r).cards.find(c=>c.id==='fluoropyrimidine-clearance');assert.deepEqual(card.trace.basis.map(x=>x.marker),[m.id]);assert.equal(card.trace.basis[0].codingName,m.allele);assert.equal(card.trace.basis[0].genomicSubstitution,`${m.reference}>${m.alternate}`);assert.equal(r.phenotype,null);assert.equal(r.diplotype,null);assert.equal(replayFindings({...r,insights:deriveInsights(r)}).verified,true);}});
test('Missing, reference and no-call DPYD results never imply drug safety',()=>{for(const mode of ['missing','reference','no-call']){let text=SAMPLE;for(const m of rules){if(mode==='missing')text=text.replace(`rs${m.id.slice(2)}\t1\t${m.position}\t${m.reference}${m.reference}\n`,'');if(mode==='no-call')text=modify(m,'--',text);}const i=deriveInsights(parseGenetics(text));assert.ok(!i.cards.some(c=>c.id==='fluoropyrimidine-clearance'));assert.equal(i.geneCoverage.find(g=>g.gene==='DPYD').detected.length,0);if(mode!=='reference')assert.equal(i.geneCoverage.find(g=>g.gene==='DPYD').called,0);}});
test('Coding-strand letters are not silently substituted for genomic alleles',()=>{assert.equal(parseGenetics(modify(rules[0],'AG')).findings.find(f=>f.id===rules[0].id).state,'unsupported');const reference=parseGenetics(modify(rules[2],'TT'));assert.equal(reference.findings.find(f=>f.id===rules[2].id).state,'not-detected');});
test('Proxy-only record never triggers a DPYD implication',()=>{const r=parseGenetics(SAMPLE+'rs56038477\t1\t97900000\tCT\n');assert.ok(!deriveInsights(r).cards.some(c=>c.id==='fluoropyrimidine-clearance'));});
test('DPYD sample and notice preserve explicit uncertainty',()=>{const r=parseGenetics(DPYD_SAMPLE),i=deriveInsights(r);assert.equal(i.pattern,'dpyd-marker');assert.deepEqual(i.cards.map(c=>c.id),['fluoropyrimidine-clearance']);assert.match(i.cards[0].trace.source.updateNotice.summary,/not been verified/);assert.equal(i.geneCoverage.find(g=>g.gene==='DPYD').called,3);const report={...r,insights:i};report.insights.cards[0].trace.source.updateNotice.summary='Current definitive guidance';assert.throws(()=>replayFindings(report),/implications differ/);});
test('Conflicting DPYD duplicates and mismatched locations reject the file',()=>{const m=rules[0];assert.throws(()=>parseGenetics(SAMPLE+`${m.id}\t1\t${m.position}\tTT\n`),/Conflicting/);assert.throws(()=>parseGenetics(SAMPLE.replace('97915614','97915613')),/location/);});
