"""Verify source bytes and selected GRCh37 substitutions; reproduce the browser rule module."""
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def reproduce(root):
    root=Path(root);raw=(root/'manifest.json').read_bytes();manifest=json.loads(raw)
    if manifest['schemaVersion']!=1:raise ValueError('Unsupported marker manifest')
    sources={}
    for source in manifest['sources']:
        path=(root/source['file']).resolve()
        if root.resolve() not in path.parents:raise ValueError('Source path escapes evidence directory')
        data=path.read_bytes()
        if len(data)!=source['bytes'] or hashlib.sha256(data).hexdigest()!=source['sha256']:raise ValueError('Marker source checksum mismatch: '+source['file'])
        sources[source['file']]=data
    rules=manifest['selectedRules']
    if len({r['id'] for r in rules})!=len(rules):raise ValueError('Duplicate rule')
    for rule in rules:
        expected={'CYP2C19':('10','NC_000010.10'),'SLCO1B1':('12','NC_000012.11'),'DPYD':('1','NC_000001.10')}.get(rule['gene'])
        if expected!=(rule['chromosome'],rule['sequence']):raise ValueError('Gene/chromosome/sequence mapping disagrees')
        if rule['gene']=='DPYD':
            complement=str.maketrans('ACGT','TGCA')
            if rule.get('codingStrand')!='negative' or not rule.get('directOnly') or (rule['reference'],rule['alternate'])!=(rule['codingReference'].translate(complement),rule['codingAlternate'].translate(complement)):raise ValueError('DPYD coding/genomic orientation disagrees')
        rs=json.loads(sources['raw/'+rule['id'][2:]+'.json'])
        if str(rs['refsnp_id'])!=rule['id'][2:]:raise ValueError('RefSNP identity mismatch')
        placements=rs['primary_snapshot_data']['placements_with_allele']
        matches=[a['allele']['spdi'] for p in placements if p['seq_id']==rule['sequence'] for a in p['alleles']]
        if not any(s['position']+1==rule['position'] and s['deleted_sequence']==rule['reference'] and s['inserted_sequence']==rule['alternate'] for s in matches):raise ValueError('Rule disagrees with captured GRCh37 placement: '+rule['id'])
    evidence_hash=hashlib.sha256(raw).hexdigest()
    payload={'manifestSha256':evidence_hash,'ruleVersion':manifest['ruleVersion'],'sources':[{'url':s['url'],'sha256':s['sha256'],'retrievedAt':s['retrievedAt']} for s in manifest['sources']]}
    output='// Generated by scripts/replay-marker-evidence.py. Do not edit.\n'
    output+='export const RULE_VERSION='+json.dumps(manifest['ruleVersion'])+';\n'
    output+='export const MARKERS=Object.freeze('+json.dumps(rules,separators=(',',':'))+'.map(Object.freeze));\n'
    output+='export const MARKER_EVIDENCE=Object.freeze('+json.dumps(payload,separators=(',',':'))+');\n'
    return output
if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    output=reproduce(ROOT/'research/marker-evidence');target=ROOT/'dist/marker-rules.mjs'
    if args.check:
        if target.read_text()!=output:raise SystemExit('Browser marker rules differ from captured evidence. Review before regenerating.')
    else:target.write_text(output)
    print('Verified marker source hashes and RefSNP placements; rule module '+('matches.' if args.check else 'generated.'))
